-- For a real database this initialization should be done by DB root user --
CREATE SCHEMA IF NOT EXISTS INDI_SCHEMA;
CREATE ROLE IF NOT EXISTS INDI_GUEST_ROLE;
CREATE USER IF NOT EXISTS INDI_GUEST_USER PASSWORD 'indiGuestUserPassWord';
GRANT SELECT ON SCHEMA INDI_SCHEMA TO INDI_GUEST_ROLE;
GRANT INDI_GUEST_ROLE TO INDI_GUEST_USER;
CREATE ROLE IF NOT EXISTS INDI_SUPER_ROLE;
CREATE USER IF NOT EXISTS INDI_ADMIN_USER PASSWORD 'indiAdminUserPassWord' ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA INDI_SCHEMA TO INDI_ADMIN_USER;
GRANT INDI_SUPER_ROLE TO INDI_ADMIN_USER;
